const SYSTEM=`Eres Rubén Coach, asistente deportivo educativo de Sumando Minutos. Responde en español, con tono cálido, respetuoso y conciso. Usa el perfil solo cuando se recibió con permiso. Separa claramente consejos generales de evidencia científica. Cita únicamente las fuentes incluidas en el contexto y jamás inventes enlaces. Para videos recomienda título, canal y enlace directo de YouTube. No diagnostiques ni sustituyas atención médica; ante dolor, lesión o riesgo recomienda detenerse y consultar a un profesional.`;
const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
async function googleSearch(q){const key=process.env.GOOGLE_SEARCH_API_KEY,cx=process.env.GOOGLE_SEARCH_ENGINE_ID;if(!key||!cx)return [];const r=await fetch(`https://www.googleapis.com/customsearch/v1?key=${encodeURIComponent(key)}&cx=${encodeURIComponent(cx)}&q=${encodeURIComponent(q)}&num=5`),d=await r.json();return r.ok?(d.items||[]).map(x=>({title:x.title,url:x.link,summary:x.snippet,source:'Google'})):[];}
async function youtubeSearch(q){const key=process.env.YOUTUBE_API_KEY;if(key){const r=await fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=4&safeSearch=strict&q=${encodeURIComponent(q)}&key=${encodeURIComponent(key)}`),d=await r.json();if(r.ok)return (d.items||[]).map(x=>({title:x.snippet.title,url:`https://www.youtube.com/watch?v=${x.id.videoId}`,summary:`Canal: ${x.snippet.channelTitle}`,source:'YouTube'}));}return googleSearch(`${q} site:youtube.com/watch`);}
async function scienceSearch(q){const r=await fetch(`https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=${encodeURIComponent(q+' AND OPEN_ACCESS:Y')}&format=json&pageSize=5`),d=await r.json();if(!r.ok)return [];return (d.resultList?.result||[]).map(x=>({title:x.title,url:x.doi?`https://doi.org/${x.doi}`:`https://europepmc.org/article/${x.source}/${x.id}`,summary:`${x.journalTitle||'Revista científica'} · ${x.pubYear||'s. f.'}`,source:'Europe PMC'}));}
exports.handler=async event=>{
  if(event.httpMethod!=='POST')return {statusCode:405,body:JSON.stringify({error:'Método no permitido'})};
  if(!process.env.OPENAI_API_KEY)return {statusCode:503,body:JSON.stringify({error:'Rubén Coach aún no está configurado'})};
  try{const body=JSON.parse(event.body||'{}');const message=String(body.message||'').trim().slice(0,1200);if(!message)return {statusCode:400,body:JSON.stringify({error:'Mensaje vacío'})};const video=/video|youtube|tutorial|liga|enlace/i.test(message),science=/investig|cient[ií]fic|evidencia|art[ií]culo|revista|estudio|paper|blog serio/i.test(message),web=/google|internet|actual|busca|enlace|fuente/i.test(message);let sources=video?await youtubeSearch(message):science?await scienceSearch(message):web?await googleSearch(message):[];sources=sources.slice(0,5);const profile=body.personalization?`Perfil autorizado: ${JSON.stringify(body.personalization)}`:'No uses personalización porque el usuario no la autorizó.';const context=sources.length?`Fuentes verificables disponibles:\n${sources.map((s,i)=>`${i+1}. ${clean(s.title)} | ${s.url} | ${clean(s.summary)}`).join('\n')}`:'No se consultaron fuentes externas para esta respuesta.';const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5-mini',instructions:SYSTEM,input:`${profile}\n${context}\nPregunta: ${message}`,max_output_tokens:500})});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Proveedor no disponible');const text=data.output_text||data.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text||'No pude responder en este momento.';return {statusCode:200,headers:{'content-type':'application/json','cache-control':'no-store'},body:JSON.stringify({reply:text,sources:sources.map(({title,url,source})=>({title:clean(title),url,source}))})};}catch(error){console.error('ruben-coach',error);return {statusCode:500,headers:{'content-type':'application/json'},body:JSON.stringify({error:'No fue posible consultar a Rubén Coach'})};}
};
